name: erp
description: "App ERP"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  intl: ^0.20.2
  fl_chart: ^0.65.0
  cupertino_icons: ^1.0.8
  dropdown_button2: ^2.3.9
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700

  assets:
    - assets/images/
    - assets/images/DigiAm/
